[2024-11-28T23:21:17.270+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-28T23:21:17.711+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Loan_Request_Report.Load manual__2024-11-28T23:05:59.234756+00:00 [queued]>
[2024-11-28T23:21:17.758+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Loan_Request_Report.Load manual__2024-11-28T23:05:59.234756+00:00 [queued]>
[2024-11-28T23:21:17.759+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-28T23:21:17.877+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Load> on 2024-11-28 23:05:59.234756+00:00
[2024-11-28T23:21:17.962+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=91) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-28T23:21:17.979+0000] {standard_task_runner.py:64} INFO - Started process 100 to run task
[2024-11-28T23:21:18.017+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Loan_Request_Report', 'Load', 'manual__2024-11-28T23:05:59.234756+00:00', '--job-id', '396', '--raw', '--subdir', 'DAGS_FOLDER/dagLoanRequest.py', '--cfg-path', '/tmp/tmpt7u4s6wy']
[2024-11-28T23:21:18.051+0000] {standard_task_runner.py:91} INFO - Job 396: Subtask Load
[2024-11-28T23:21:18.771+0000] {task_command.py:426} INFO - Running <TaskInstance: Loan_Request_Report.Load manual__2024-11-28T23:05:59.234756+00:00 [running]> on host 97460a9713a2
[2024-11-28T23:21:20.817+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Loan_Request_Report' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T23:05:59.234756+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T23:05:59.234756+00:00'
[2024-11-28T23:21:20.827+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-28T23:21:21.242+0000] {logging_mixin.py:188} INFO - -----Load---
[2024-11-28T23:21:21.243+0000] {logging_mixin.py:188} INFO - ----------------------------------------before---------------------
[2024-11-28T23:21:22.590+0000] {logging_mixin.py:188} INFO - Error during subprocess execution: Command '['docker', 'cp', 'loanrequestvisualization-***-webserver-1:/tmp/transformed_data_2024-10-29.csv', '/tmp/transformed_data_2024-10-29.csv']' returned non-zero exit status 1.
[2024-11-28T23:21:22.624+0000] {logging_mixin.py:188} INFO - -----------------------------done-----------------------
[2024-11-28T23:21:24.182+0000] {hive.py:475} INFO - USE `m2t`
[2024-11-28T23:21:26.299+0000] {hive.py:475} INFO - TRUNCATE TABLE M2T.OUTPUT_TABLE_ETL
[2024-11-28T23:22:02.437+0000] {hive.py:475} INFO - LOAD DATA LOCAL INPATH '/opt/transformed_data_2024-10-29.csv' INTO TABLE M2T.OUTPUT_TABLE_ETL
[2024-11-28T23:22:18.721+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-28T23:22:18.752+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-28T23:22:19.054+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Loan_Request_Report, task_id=Load, run_id=manual__2024-11-28T23:05:59.234756+00:00, execution_date=20241128T230559, start_date=20241128T232117, end_date=20241128T232219
[2024-11-28T23:22:19.184+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-28T23:22:19.271+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
