[2024-11-06T11:40:05.651+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-06T11:40:05.734+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Loan_Request_Report.Transform manual__2024-11-06T11:37:31+00:00 [queued]>
[2024-11-06T11:40:05.756+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Loan_Request_Report.Transform manual__2024-11-06T11:37:31+00:00 [queued]>
[2024-11-06T11:40:05.756+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-06T11:40:05.785+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Transform> on 2024-11-06 11:37:31+00:00
[2024-11-06T11:40:05.800+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=152) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-06T11:40:05.804+0000] {standard_task_runner.py:64} INFO - Started process 154 to run task
[2024-11-06T11:40:05.802+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Loan_Request_Report', 'Transform', 'manual__2024-11-06T11:37:31+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dagLoanRequest.py', '--cfg-path', '/tmp/tmp28ceedh0']
[2024-11-06T11:40:05.806+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask Transform
[2024-11-06T11:40:05.928+0000] {task_command.py:426} INFO - Running <TaskInstance: Loan_Request_Report.Transform manual__2024-11-06T11:37:31+00:00 [running]> on host f4ed2a87aeca
[2024-11-06T11:40:06.295+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Loan_Request_Report' AIRFLOW_CTX_TASK_ID='Transform' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T11:37:31+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T11:37:31+00:00'
[2024-11-06T11:40:06.304+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-06T11:40:06.641+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-06T11:40:06.642+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dagLoanRequest.py", line 38, in transform_task
    transformed_df = Transform_data(merged_df)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etlProcess.py", line 74, in Transform_data
    df['DATE_REMBOURSEMENT_DERNIERE_ECHEANCE'] = df.apply(calculate_date_remboursement, axis=1)
    ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4081, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4239, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column DATE_REMBOURSEMENT_DERNIERE_ECHEANCE
[2024-11-06T11:40:06.676+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Loan_Request_Report, task_id=Transform, run_id=manual__2024-11-06T11:37:31+00:00, execution_date=20241106T113731, start_date=20241106T114005, end_date=20241106T114006
[2024-11-06T11:40:06.710+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 53 for task Transform (Cannot set a DataFrame with multiple columns to the single column DATE_REMBOURSEMENT_DERNIERE_ECHEANCE; 154)
[2024-11-06T11:40:06.769+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-06T11:40:06.818+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-06T11:40:06.825+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
