[2024-11-04T08:26:57.701+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-04T08:26:58.012+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Loan_Request_Report.Extract manual__2024-11-04T08:26:10.193187+00:00 [queued]>
[2024-11-04T08:26:58.081+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Loan_Request_Report.Extract manual__2024-11-04T08:26:10.193187+00:00 [queued]>
[2024-11-04T08:26:58.083+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-04T08:26:58.248+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Extract> on 2024-11-04 08:26:10.193187+00:00
[2024-11-04T08:26:58.333+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Loan_Request_Report', 'Extract', 'manual__2024-11-04T08:26:10.193187+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dagLoanRequest.py', '--cfg-path', '/tmp/tmp54__z5wb']
[2024-11-04T08:26:58.344+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask Extract
[2024-11-04T08:26:58.345+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=163) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-04T08:26:58.362+0000] {standard_task_runner.py:64} INFO - Started process 171 to run task
[2024-11-04T08:26:58.819+0000] {task_command.py:426} INFO - Running <TaskInstance: Loan_Request_Report.Extract manual__2024-11-04T08:26:10.193187+00:00 [running]> on host f4ed2a87aeca
[2024-11-04T08:26:59.978+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Loan_Request_Report' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T08:26:10.193187+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-04T08:26:10.193187+00:00'
[2024-11-04T08:26:59.992+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-04T08:27:00.006+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-04T08:27:00.008+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dagLoanRequest.py", line 31, in extract_task
    merged_df, original_df = extract_data_from_hive(kwargs['required_date'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etlProcess.py", line 84, in extract_data_from_hive
    conn = hive.Connection(host="hive-server", port=10000, database='m2t')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyhive/hive.py", line 242, in __init__
    import thrift_sasl
ModuleNotFoundError: No module named 'thrift_sasl'
[2024-11-04T08:27:00.248+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Loan_Request_Report, task_id=Extract, run_id=manual__2024-11-04T08:26:10.193187+00:00, execution_date=20241104T082610, start_date=20241104T082658, end_date=20241104T082700
[2024-11-04T08:27:00.613+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task Extract (No module named 'thrift_sasl'; 171)
[2024-11-04T08:27:00.676+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-04T08:27:01.043+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-04T08:27:01.066+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
