[2024-11-07T19:39:35.179+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-07T19:39:35.366+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Loan_Request_Report.Extract manual__2024-11-07T19:38:44.886687+00:00 [queued]>
[2024-11-07T19:39:35.410+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Loan_Request_Report.Extract manual__2024-11-07T19:38:44.886687+00:00 [queued]>
[2024-11-07T19:39:35.411+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-07T19:39:35.550+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Extract> on 2024-11-07 19:38:44.886687+00:00
[2024-11-07T19:39:35.584+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=374) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-07T19:39:35.591+0000] {standard_task_runner.py:64} INFO - Started process 382 to run task
[2024-11-07T19:39:35.601+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Loan_Request_Report', 'Extract', 'manual__2024-11-07T19:38:44.886687+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/dagLoanRequest.py', '--cfg-path', '/tmp/tmp7o8y4_hn']
[2024-11-07T19:39:35.615+0000] {standard_task_runner.py:91} INFO - Job 185: Subtask Extract
[2024-11-07T19:39:36.028+0000] {task_command.py:426} INFO - Running <TaskInstance: Loan_Request_Report.Extract manual__2024-11-07T19:38:44.886687+00:00 [running]> on host 2bac939b7bc7
[2024-11-07T19:39:36.999+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Loan_Request_Report' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-07T19:38:44.886687+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-07T19:38:44.886687+00:00'
[2024-11-07T19:39:37.002+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-07T19:39:37.014+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-07T19:39:37.015+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dagLoanRequest.py", line 31, in extract_task
    merged_df, original_df = extract_data_from_hive(kwargs['required_date'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etlProcess.py", line 86, in extract_data_from_hive
    conn = hive.Connection(host="hive-server", port=10000, database='m2t')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyhive/hive.py", line 242, in __init__
    import thrift_sasl
ModuleNotFoundError: No module named 'thrift_sasl'
[2024-11-07T19:39:37.058+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Loan_Request_Report, task_id=Extract, run_id=manual__2024-11-07T19:38:44.886687+00:00, execution_date=20241107T193844, start_date=20241107T193935, end_date=20241107T193937
[2024-11-07T19:39:37.120+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 185 for task Extract (No module named 'thrift_sasl'; 382)
[2024-11-07T19:39:37.173+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-07T19:39:37.408+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-07T19:39:37.453+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
